---
# GitHub Workflow for building and deploying a Hugo site to GitHub Pages
# needs secrets.MRX_DOCKER_USR - account username for docker hub
# needs secrets.MRX_DOCKER_PAT - account access token for docker hub
# needs    vars.MRX_DOCKER_NS  - account namespace for docker hub e.g. mrmxf
name: pr-build-push

on:
  # Runs on push to main branch
  pull_request:
    types: [closed]
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# global environment
env:
  # This overrides the values in clogrc/_cfg.sh
  vNODE: 20.15

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages:    write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: set the ENV
        run: |
              source clogrc/_cfg.sh
              echo "Deploying website version ($vCODE) from branch ($BRANCH)"
              echo "vCODE=$vCODE"     >> $GITHUB_ENV
              echo "BRANCH=$BRANCH"   >> $GITHUB_ENV
              echo "PROJECT=$PROJECT" >> $GITHUB_ENV
              echo "pushing to hub: ${{ vars.MRX_DOCKER_NS  }}/${{ env.IMAGE  }}:$vCODE"
      -
        name: Bark some context vairables
        uses: mrmxf/action-bark@0.2.05
      -
        name: check the ENV
        run:  |
              echo "pushing to hub: ${{ vars.MRX_DOCKER_NS  }}/${{ env.IMAGE  }}:${{ env.vCODE }}"

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: '${{ github.workspace }}/go.mod'
      - run: |
          go test ./...
